export const rolePermissions = {
  superadmin: [
    "dashboard",
     "Home",
    "user-management",
    "create-user",
    "bulk-upload",
    "reports",
    "products",
    "orders",
    "add-product",
    "rates",
    "calculator",
    "LandingPage",
    "metal-ledger",
     "invoices",
    "returns",
    "credit-notes",
    "manual-billing",
    "expenses",
     "inquiries",
     "quotation",
     "suppliers",
     "catalogues",
  ],

  admin: [
    "dashboard",
     "Home",
    "rates",
    "user-management",
    "create-user",
    "reports",
     "calculator",
    "products",
    "orders",
   "bulk-upload",
    "LandingPage",
    "add-product",
    "metal-ledger",
    "invoices",
    "returns",
    "credit-notes",
    "manual-billing",
    "expenses",
    "inquiries",
    "gst-reports",
    "quotation",
    "suppliers",
    "catalogues",
  ],


  manager: [
    "dashboard",
    "add-product",
     "Home",
    "reports",
    "orders",
  ],

  salesperson: [
     "dashboard",
     "Home",
    "reports",
     "calculator",
    "orders",
    "add-product",
    "sales-invoices",
    "daily-sales-closing",
    "products",
    "inquiries",
    "quotation",
    "catalogues",
  ],


  accountant: [
    "dashboard",
    "sales-invoices",
     "Home",
    "reports",
    "daily-sales-closing",
  ],

  inventory: [
    "products",
      "Home",
      "calculator",
      "orders",
      "add-product",
  ],
};
